use_frameworks!

platform :ios, '10.0'

target 'MKTestProject_Example' do
  pod 'MKTestProject', :path => '../'

  target 'MKTestProject_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
